
- name: get oauth2_proxy
  get_url: >
    url=https://github.com/bitly/oauth2_proxy/releases/download/v2.0.1/oauth2_proxy-2.0.1.linux-amd64.go1.4.2.tar.gz
    dest=/usr/local/src/

- name: unarchive oauth2_proxy
  unarchive: src=/usr/local/src/oauth2_proxy-2.0.1.linux-amd64.go1.4.2.tar.gz dest=/tmp/ copy=no

- name: move oauth2_proxy
  shell: mv /tmp/oauth2_proxy-2.0.1.linux-amd64.go1.4.2/oauth2_proxy /usr/bin/

- name: create /etc/oauth2_proxy
  file: path=/etc/oauth2_proxy state=directory mode=0700
  
- name: config setting
  copy: src=oauth2_proxy.conf dest=/etc/oauth2_proxy/oauth2_proxy.conf mode=0644